-- NFL DISTANCES
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (870,'State Farm Stadium','Arizona Cardinals','AT&T Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (650,'State Farm Stadium','Arizona Cardinals','Levis Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1115,'State Farm Stadium','Arizona Cardinals','NRG Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (580,'State Farm Stadium','Arizona Cardinals','Broncos Stadium at Mile High');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (372,'State Farm Stadium','Arizona Cardinals','Sofi Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (740,'Mercedes-Benz Stadium','Atlanta Falcons','AT&T Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (225,'Mercedes-Benz Stadium','Atlanta Falcons','Bank of America Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (600,'Mercedes-Benz Stadium','Atlanta Falcons','Hard Rock Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (425,'Mercedes-Benz Stadium','Atlanta Falcons','Mercedes-Benz Superdome');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (375,'Mercedes-Benz Stadium','Atlanta Falcons','Paul Brown Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (90,'M&T Bank Stadium','Baltimore Ravens','FedExField');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (80,'M&T Bank Stadium','Baltimore Ravens','Lincoln Financial Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (210,'Bills Stadium','Buffalo Bills','Ford Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (429,'Bills Stadium','Buffalo Bills','Gillette Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (225,'Bills Stadium','Buffalo Bills','Heinz Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (430,'Bills Stadium','Buffalo Bills','Lambeau Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (2070,'Bills Stadium','Buffalo Bills','CenturyLink Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (342,'Bank of America Stadium','Carolina Panthers','TIAA Bank Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (340,'Bank of America Stadium','Carolina Panthers','FedExField');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (225,'Bank of America Stadium','Carolina Panthers','Mercedes-Benz Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (365,'Bank of America Stadium','Carolina Panthers','Heinz Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (415,'Soldier Field','Chicago Bears','Arrowhead Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (80,'Soldier Field','Chicago Bears','Lambeau Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (50,'Soldier Field','Chicago Bears','Lucas Oil Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (225,'Paul Brown Stadium','Cincinnati Bengals','FirstEnergy Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (375,'Paul Brown Stadium','Cincinnati Bengals','Mercedes-Benz Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (260,'Paul Brown Stadium','Cincinnati Bengals','Heinz Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (250,'Paul Brown Stadium','Cincinnati Bengals','Lucas Oil Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (240,'Paul Brown Stadium','Cincinnati Bengals','Nissan Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (90,'FirstEnergy Stadium','Cleveland Browns','Ford Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (115,'FirstEnergy Stadium','Cleveland Browns','Heinz Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (225,'FirstEnergy Stadium','Cleveland Browns','Paul Brown Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (460,'AT&T Stadium','Dallas Cowboys','Arrowhead Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (740,'AT&T Stadium','Dallas Cowboys','Mercedes-Benz Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (230,'AT&T Stadium','Dallas Cowboys','NRG Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (650,'AT&T Stadium','Dallas Cowboys','Broncos Stadium at Mile High');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (870,'AT&T Stadium','Dallas Cowboys','State Farm Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (650,'Broncos Stadium at Mile High','Denver Broncos','AT&T Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (560,'Broncos Stadium at Mile High','Denver Broncos','Arrowhead Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (930,'Broncos Stadium at Mile High','Denver Broncos','Levis Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1015,'Broncos Stadium at Mile High','Denver Broncos','Sofi Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (580,'Broncos Stadium at Mile High','Denver Broncos','State Farm Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (90,'Ford Field','Detroit Lions','FirstEnergy Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (240,'Ford Field','Detroit Lions','Lucas Oil Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (210,'Ford Field','Detroit Lions','Bills Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (430,'Lambeau Field','Green Bay Packers','Bills Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (80,'Lambeau Field','Green Bay Packers','Soldier Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (300,'Lambeau Field','Green Bay Packers','U.S. Bank Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (230,'NRG Stadium','Houston Texans','AT&T Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (965,'NRG Stadium','Houston Texans','Hard Rock Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (320,'NRG Stadium','Houston Texans','Mercedes-Benz Superdome');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (670,'NRG Stadium','Houston Texans','Nissan Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1115,'NRG Stadium','Houston Texans','State Farm Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (240,'Lucas Oil Stadium','Indianapolis Colts','Ford Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (250,'Lucas Oil Stadium','Indianapolis Colts','Paul Brown Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (50,'Lucas Oil Stadium','Indianapolis Colts','Soldier Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (342,'TIAA Bank Field','Jacksonville Jaguars','Bank of America Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (170,'TIAA Bank Field','Jacksonville Jaguars','Raymond James Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (315,'TIAA Bank Field','Jacksonville Jaguars','Hard Rock Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (460,'Arrowhead Stadium','Kansas City Chiefs','AT&T Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (470,'Arrowhead Stadium','Kansas City Chiefs','Nissan Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (415,'Arrowhead Stadium','Kansas City Chiefs','Soldier Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (560,'Arrowhead Stadium','Kansas City Chiefs','Broncos Stadium at Mile High');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (15,'Sofi Stadium','Los Angeles Chargers','Sofi Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1015,'Sofi Stadium','Los Angeles Chargers','Broncos Stadium at Mile High');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (372,'Sofi Stadium','Los Angeles Chargers','State Farm Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (200,'Sofi Stadium','Los Angeles Rams','Levis Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (270,'Sofi Stadium','Los Angeles Rams','Allegiant Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (15,'Sofi Stadium','Los Angeles Rams','Sofi Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1500,'Sofi Stadium','Los Angeles Rams','U.S. Bank Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (315,'Hard Rock Stadium','Miami Dolphins','TIAA Bank Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (600,'Hard Rock Stadium','Miami Dolphins','Mercedes-Benz Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1255,'Hard Rock Stadium','Miami Dolphins','Gillette Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (965,'Hard Rock Stadium','Miami Dolphins','NRG Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (210,'Hard Rock Stadium','Miami Dolphins','Raymond James Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1390,'U.S. Bank Stadium','Minnesota Vikings','CenturyLink Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (300,'U.S. Bank Stadium','Minnesota Vikings','Lambeau Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (700,'U.S. Bank Stadium','Minnesota Vikings','Nissan Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1500,'U.S. Bank Stadium','Minnesota Vikings','Sofi Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1255,'Gillette Stadium','New England Patriots','Hard Rock Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (429,'Gillette Stadium','New England Patriots','Bills Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (195,'Gillette Stadium','New England Patriots','MetLife Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (425,'Mercedes-Benz Superdome','New Orleans Saints','Mercedes-Benz Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (320,'Mercedes-Benz Superdome','New Orleans Saints','NRG Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (480,'Mercedes-Benz Superdome','New Orleans Saints','Raymond James Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (195,'MetLife Stadium','New York Giants','Gillette Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (50,'MetLife Stadium','New York Giants','Lincoln Financial Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (195,'MetLife Stadium','New York Jets','Gillette Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (50,'MetLife Stadium','New York Jets','Lincoln Financial Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1275,'Allegiant Stadium','Las Vegas Raiders','CenturyLink Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (569,'Allegiant Stadium','Las Vegas Raiders','Levis Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (270,'Allegiant Stadium','Las Vegas Raiders','Sofi Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (315,'Lincoln Financial Field','Philadelphia Eagles','Heinz Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (80,'Lincoln Financial Field','Philadelphia Eagles','M&T Bank Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (50,'Lincoln Financial Field','Philadelphia Eagles','MetLife Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (365,'Heinz Field','Pittsburgh Steelers','Bank of America Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (115,'Heinz Field','Pittsburgh Steelers','FirstEnergy Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (315,'Heinz Field','Pittsburgh Steelers','Lincoln Financial Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (260,'Heinz Field','Pittsburgh Steelers','Paul Brown Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (225,'Heinz Field','Pittsburgh Steelers','Bills Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (569,'Levis Stadium','San Francisco 49ers','Allegiant Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (930,'Levis Stadium','San Francisco 49ers','Broncos Stadium at Mile High');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (200,'Levis Stadium','San Francisco 49ers','Sofi Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (650,'Levis Stadium','San Francisco 49ers','State Farm Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1270,'CenturyLink Field','Seattle Seahawks','Allegiant Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (2070,'CenturyLink Field','Seattle Seahawks','Bills Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (1390,'CenturyLink Field','Seattle Seahawks','U.S. Bank Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (170,'Raymond James Stadium','Tampa Bay Buccaneers','TIAA Bank Field');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (210,'Raymond James Stadium','Tampa Bay Buccaneers','Hard Rock Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (480,'Raymond James Stadium','Tampa Bay Buccaneers','Mercedes-Benz Superdome');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (470,'Nissan Stadium','Tennessee Titans','Arrowhead Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (670,'Nissan Stadium','Tennessee Titans','NRG Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (240,'Nissan Stadium','Tennessee Titans','Paul Brown Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (700,'Nissan Stadium','Tennessee Titans','U.S. Bank Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (340,'FedExField','Washington Redskins','Bank of America Stadium');
INSERT INTO nfldistances (`distance`,`beginningstadium`,`teamname`,`endingstadium`) VALUES (90,'FedExField','Washington Redskins','M&T Bank Stadium');

-- NFL INFORMATION

INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC West','State Farm Stadium',63400,'Bermuda Grass','Arizona Cardinals','Retractable','Glendale, Arizona',2026);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC South','Mercedes-Benz Stadium',71000,'FieldTurf Classic HD','Atlanta Falcons','Fixed','Atlanta, Georgia',2017);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC North','M&T Bank Stadium',71008,'Bermuda Grass','Baltimore Ravens','Open','Baltimore, Maryland',1998);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC East','Bills Stadiuim',71608,'A-Turf Titan 50','Buffalo Bills','Open','Orchard Park, New York',1973);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC South','Bank of America Stadium',75419,'Bermuda Grass','Carolina Panthers','Open','Charlotte, North Carolina',1996);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC North','Soldier Field',61500,'Kentucky Bluegrass','Chicago Bears','Open','Chicago, Illinois',1924);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC North','Paul Brown Stadium',65515,'UBU Speed Series S5-M Synthetic Turf','Cincinnati Bengals','Open','Cincinnati, Ohio',2000);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC North','FirstEnergy Stadium',67895,'Kentucky Bluegrass','Cleveland Browns','Open','Cleveland, Ohio',1999);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC East','AT&T Stadium',80000,'Hellas Matrix Turf','Dallas Cowboys','Retractable','Arlington, Texas',2009);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC West','Empower Field at Mile High',76125,'Kentucky Bluegrass','Denver Broncos','Open','Denver, Colorado',2001);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC North','Ford Field',65000,'FieldTurf Classic HD','Detroit Lions','Fixed','Detroit, Michigan',2002);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC North','Lambeau Field',81435,'Desso GrassMaster','Green Bay Packers','Open','Green Bay, Wisconsin',1957);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC South','NRG Stadium',72220,'Hellas Matrix Turf','Houston Texans','Retractable','Houston, Texas',2002);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC South','Lucas Oil Stadium',67000,'FieldTurf Classic HD','Indianapolis Colts','Retractable','Indianapolis, Indiana',2008);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC South','TIAA Bank Field',69132,'Bermuda Grass','Jacksonville Jaguars','Open','Jacksonville, Florida',1995);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC West','Arrowhead Stadium',76416,'Bermuda Grass','Kansas City Chiefs','Open','Kansas City, Missouri',1972);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC West','Allegiant Stadium ',65000,'Bermuda Grass','Las Vegas Raiders','Fixed','Paradise, Nevada',2020);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC West','SoFi Stadium',70240,'Bermuda Grass','Los Angeles Chargers','Fixed','Inglewood, California',2020);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC West','SoFi Stadium',70240,'Bermuda Grass','Los Angeles Rams','Fixed ','Inglewood, California',2020);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC East','Hard Rock Stadium',65326,'Platinum TE Paspalum','Miami Dolphins','Open','Miami Gardens, Florida',1987);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC North','U.S. Bank Stadium',66655,'UBU Speed Series S5-M Synthetic Turf','Minnesota Vikings','Fixed','Minneapolis, Minnesota',2016);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC East','Gillette Stadium',66829,'FieldTurf Revolution','New England Patriots','Open','Foxborough, Massachusetts',2002);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC South','Mercedes-Benz Superdome',73000,'UBU Sports Speed Series S5-M Synthetic Turf','New Orleans Saints','Fixed','New Orleans, Louisiana',1975);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC East','MetLife Stadium',82500,'UBU Sports Speed Series S5-M Synthetic Turf','New York Giants','Open','East Rutherford, New Jersey',2010);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC East','MetLife Stadium',82500,'UBU Sports Speed Series S5-M Synthetic Turf','New York Jets','Open','East Rutherford, New Jersey',2010);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC East','Lincoln Financial Field',69596,'Desso GrassMaster','Philadelphia Eagles','Open','Philadelphia, Pennsylvania',2003);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC North','Heinz Field',68400,'Kentucky Bluegrass','Pittsburgh Steelers','Open','Pittsburgh, Pennsylvania',2001);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC West','Levis Stadium',68500,'Bermuda Grass','San Francisco 49ers','Open','Santa Clara, California',2014);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC West','CenturyLink Field',68000,'FieldTurf Revolution','Seattle Seahawks','Open','Seattle, Washington',2002);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC South','Raymond James Stadium',65890,'Bermuda Grass','Tampa Bay Buccaneers','Open','Tampa, Florida',1998);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('American Football Conference','AFC South','Nissan Stadium',69143,'Bermuda Grass','Tennessee Titans','Open','Nashville, Tennessee',1999);
INSERT INTO nflinformation (`conference`,`division`,`stadiumname`,`seatingcapacity`,`surfacetype`,`teamname`,`stadiumrooftype`,`location`,`dateopened`) VALUES ('National Football Conference','NFC East','FedExField',82000,'Bermuda Grass','Washington Football Team','Open','Landover, Maryland',1997);
